version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_sqcoins
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sqcoins123
      MYSQL_DATABASE: sqcoins
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_sqcoins
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: sqcoins123
      DB_NAME: sqcoins
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app       
      - ./frontend:/usr/src/frontend 
    command: node index.js


volumes:
  db_data:
